### ISSUE TITLE
[Team]: Create Post-release checklist

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#541]
Create and document a Post-release checklist for various tasks that should happen every time a release is out:

## For major releases

Immediately after release:
- [x] Update internal Slack and Gitter with links to the latest release and change log.
- [ ] Update social media with latest release and change log.
- [ ] Decide if the release is important enough for a major blog post. If it is, assign blog post writer. Post should include instructions on how to upgrade.

Assign Community Engineers to:
- [ ] Test all major plugin tutorial repositories, YouTube videos against the latest release. If plugins fail, make issues for Plugins, Tutorials and/or Core.
- [ ] Test all major plugins against the latest release. If plugins fail, make issues for Plugins, Tutorials and/or Core.

List of plugins and tutorials to test:
- reaction-example-plugin
- reaction-swag-shop
- reaction-devtools
- YouTube video tutorials

Assign Documentation to:
- [x] Tag a Documentation release
- [ ] For any *new* Documentation tutorial links, new FAQ questions, add @sophiehe to the PR with a URL to it so she can tweet it.

## For minor releases

Immediately after release:
- [x] Update internal Slack and Gitter with links to the latest release and change log.
